baseurl = "/"
languageCode = "en-us"
title = "pharmaR website"
theme = "hugo-universal-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = 1
[[menu.main]]
    parent = "about"
		name = "About Us"
    url = "/about/"
    weight = 12
[[menu.main]]
    parent = "about"
		name = "Partner Initiatives"
    url = "/partners/"
    weight = 13
[[menu.main]]
    parent = "about"
		name = "Roadmap"
    url = "/roadmap/"
    weight = 14
[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2
[[menu.main]]
    identifier = "regulations"
		name = "Regulations"
    url = "/regulations/"
    weight = 3
[[menu.main]]
    identifier = "valid"
		name = "Validation"
    url = "/valid/"
    weight = 4
[[menu.main]]
    parent = "valid"
		name = "Overview"
    url = "/overview/"
    weight = 41
[[menu.main]]
    parent = "valid"
		name = "R"
    url = "/r/"
    weight = 42
[[menu.main]]
    parent = "valid"
    name = "Risk Assessment"
    url = "/risk/"
    weight = 43
[[menu.main]]
    parent = "valid"
    name = "Examples"
    url = "/examples/"
    weight = 44
[[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 5
[[menu.main]]
    parent = "resources"
    name = "Minutes"
    url = "/minutes/"
    weight = 51
[[menu.main]]
    parent = "resources"
    name = "Presentations"
    url = "/present/"
    weight = 52
[[menu.main]]
    parent = "resources"
    name = "White Paper"
    url = "/white-paper/"
    weight = 43
[[menu.main]]
    name = "Contact Us"
    url = "/contact/"
    weight = 8

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    style = "blue"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/pharmaRlogo.png"
    logo_small = "img/pharmaRlogo_small.png"
	
    email = "psi.aims.r.validation@gmail.com"
		
[params.carousel]
    enable = true
		
[params.clients]
    enable = true
    title = "Participating Organisations"
    subtitle = "Members of the following organisations are participating in this project"

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Recent blog posts"
    
[params.widgets]
    search = true
    categories = true
    tags = true
		
[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"		
		
[params.topbar]
    enable = true
    text = "<p>Contact us at psi.aims.r.validation@gmail.com.</p>"
    

