baseurl = "/"
languageCode = "en-us"
title = "pharmaR website"
theme = "hugo-universal-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[menu.main]]
    name       = "About Us"
    identifier = "menu.about"
    url        = "/img/rval_pattern.png"
    weight     = 1

[[menu.main]]
    name       = "The R Validation Hub"
    identifier = "section.rvalhub"
    url        = ""
    weight     = 1
    parent     = "menu.about"
    post       = 1

[[menu.main]]
    name       = "Our Mission & History"
    url        = "/mission-and-history/"
    weight     = 1
    parent     = "section.rvalhub"

[[menu.main]]
    name       = "Participating Organizations"
    url        = "/participating-orgs/"
    weight     = 12
    parent     = "section.rvalhub"
    
[[menu.main]]
    name       = "Partner Initiatives"
    url        = "/partner-initiatives/"
    weight     = 13
    parent     = "section.rvalhub"
    
[[menu.main]]
    name       = "Our Team"
    identifier = "section.team"
    url        = ""
    weight     = 2
    parent     = "menu.about"
    post       = 2

[[menu.main]]
    name       = "Team Members"
    url        = "/meet-the-team/"
    weight     = 21
    parent     = "section.team"

[[menu.main]]
    name       = "Our Workstreams"
    url        = "/workstreams/"
    weight     = 22
    parent     = "section.team"
    
[[menu.main]]
    name       = "Validation"
    identifier = "menu.validation"
    url        = "/img/package_pattern.png"
    weight     = 3

[[menu.main]]
    name       = "Why Validation?"
    identifier = "section.why"
    url        = ""
    weight     = 1
    parent     = "menu.validation"
    post       = 1

[[menu.main]]
    name       = "Test"
    url        = "/test/"
    weight     = 1
    parent     = "section.why"
    
[[menu.main]]
    name       = "Our Validation Approaches"
    identifier = "section.how"
    url        = ""
    weight     = 2
    parent     = "menu.validation"
    post       = 2

[[menu.main]]
    name       = "The {riskmetric} Package"
    url        = "/riskmetric/"
    weight     = 21
    parent     = "section.how"
    
[[menu.main]]
    name       = "The {riskassessment} App"
    url        = "/riskassessment/"
    weight     = 22
    parent     = "section.how"
    
[[menu.main]]
    name       = "Our White Paper"
    url        = "/white-paper/"
    weight     = 23
    parent     = "section.how"

[[menu.main]]
    name       = "General Guidances"
    url        = "/guidances/"
    weight     = 24
    parent     = "section.how"
    
[[menu.main]]
    name = "Case Studies"
    url  = "/casestudies/"
    weight = 4
[[menu.main]]
    identifier = "roadmap"
    name = "Our Roadmap"
    url = "/our-roadmap/"
    weight = 5
[[menu.main]]
    parent = "roadmap"
    name = "Accomplishments"
    url = "/accomplishments/"
    weight = 51
[[menu.main]]
    parent = "roadmap"
    name = "Looking Forward"
    url = "/looking-forward/"
    weight = 52
[[menu.main]]
    parent = "roadmap"
    name = "Blog/LinkedIn Updates"
    url = "/updates/"
    weight = 53
[[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 6
[[menu.main]]
    parent = "resources"
    name = "Presentations"
    url = "/present/"
    weight = 61
[[menu.main]]
    parent = "resources"
    name = "Papers"
    url = "/white-paper/"
    weight = 62
[[menu.main]]
    parent = "resources"
    name = "Minutes"
    url = "/minutes/"
    weight = 63
[[menu.main]]
    parent = "resources"
    name = "Glossary"
    url = "/glossary/"
    weight = 64
[[menu.main]]
    identifier = "involved"
    name = "Get Involved"
    url = "/involved/"
    weight = 7
[[menu.main]]
    parent = "involved"
    name = "Community Meetings"
    url = "/community-meetings/"
    weight = 71
    [[menu.main]]
    parent = "involved"
    name = "Contribute"
    url = "/contribute/"
    weight = 72
[[menu.main]]
    parent = "involved"
    name = "Contact Us"
    url = "/contact/"
    weight = 73

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    style = "blue"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/pharmaRlogo.png"
    logo_small = "img/pharmaRlogo_small.png"

    email = "psi.aims.r.validation@gmail.com"

[params.carousel]
    enable = true

[params.clients]
    enable = true
    title = "Participating Organisations"
    subtitle = "Members of the following organisations are participating in this project"

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Recent blog posts"

[params.widgets]
    search = true
    categories = true
    tags = true

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params.topbar]
    enable = true
    text = "<p>Contact us at psi.aims.r.validation@gmail.com.</p>"
