baseurl = "/"
languageCode = "en-us"
title = "pharmaR website"
theme = "hugo-universal-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = 1
[[menu.main]]
    parent = "about"
    name = "About the R Validation Hub"
    url = "/about-rval/"
    weight = 12
[[menu.main]]
    parent = "about"
    name = "Meet the Team"
    url = "/meet-the-team/"
    weight = 13
[[menu.main]]
    parent = "about"
    name = "Partner Initiatives"
    url = "/partners/"
    weight = 14
    [[menu.main]]
    parent = "about"
    name = "Participating Organizations"
    url = "/participating-orgs/"
    weight = 14
[[menu.main]]
    name = "Why Validation?"
    url  = "/why-val/"
    weight = 2
[[menu.main]]
    identifier = "how-val"
    name = "How Validation?"
    url = "/how-val/"
    weight = 3
[[menu.main]]
    parent = "how-val"
    name = "{riskmetric}"
    url = "/riskmetric/"
    weight = 31
[[menu.main]]
    parent = "how-val"
    name = "{riskassessment}"
    url = "/riskassessment/"
    weight = 32
[[menu.main]]
    parent = "how-val"
    name = "White Paper"
    url = "/white-paper/"
    weight = 33
[[menu.main]]
    parent = "how-val"
    name = "Guidances"
    url = "/guidances/"
    weight = 34
[[menu.main]]
    name = "Case Studies"
    url  = "/casestudies/"
    weight = 4
[[menu.main]]
    identifier = "roadmap"
    name = "Our Roadmap"
    url = "/our-roadmap/"
    weight = 5
[[menu.main]]
    parent = "roadmap"
    name = "Accomplishments"
    url = "/accomplishments/"
    weight = 51
[[menu.main]]
    parent = "roadmap"
    name = "Looking Forward"
    url = "/looking-forward/"
    weight = 52
[[menu.main]]
    parent = "roadmap"
    name = "Blog/LinkedIn Updates"
    url = "/updates/"
    weight = 53
[[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 6
[[menu.main]]
    parent = "resources"
    name = "Presentations"
    url = "/present/"
    weight = 61
[[menu.main]]
    parent = "resources"
    name = "Papers"
    url = "/white-paper/"
    weight = 62
[[menu.main]]
    parent = "resources"
    name = "Minutes"
    url = "/minutes/"
    weight = 63
[[menu.main]]
    parent = "resources"
    name = "Glossary"
    url = "/glossary/"
    weight = 64
[[menu.main]]
    identifier = "involved"
    name = "Get Involved"
    url = "/involved/"
    weight = 7
[[menu.main]]
    parent = "involved"
    name = "Contribute"
    url = "/contribute/"
    weight = 71
[[menu.main]]
    parent = "involved"
    name = "Contact Us"
    url = "/contact/"
    weight = 72

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    style = "blue"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/pharmaRlogo.png"
    logo_small = "img/pharmaRlogo_small.png"

    email = "psi.aims.r.validation@gmail.com"

[params.carousel]
    enable = true

[params.clients]
    enable = true
    title = "Participating Organisations"
    subtitle = "Members of the following organisations are participating in this project"

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Recent blog posts"

[params.widgets]
    search = true
    categories = true
    tags = true

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params.topbar]
    enable = true
    text = "<p>Contact us at psi.aims.r.validation@gmail.com.</p>"
