---
title: 'Some Considerations on Trusted Resources'
author: Juliane Manitz and Yilong Zhang
date: '2021-12-10'
slug: trusted-resources
categories:
  - news
banner: 'img/banners/news.png'
---

There is a large variety of contributed R packages, which can be overwhelming when performing their accuracy assessment.These packages can be developed by anyone and may differ in accuracy. The [white paper](https://www.pharmar.org/white-paper/) mentions the possibility to define “trusted resources” to simplify the assessment for some of the R packages. 

The idea follows vendor assessments / audits to explore the internal validation practices of the vendor for proprietary software. For open-source software such audits are not logistically feasible. However, based on information available in the open-source domain, it may still be possible to perform a virtual audit of a vendor and their practices. In this context, we encourage the publication of software development life cycles (SDLC) documents, which support the process of risk assessment and provide evidence of software trustworthiness.  

Early on, the R Foundation and R Core team have published information about their software development practices in [R: Regulatory Compliance and Validation Issues. A Guidance Document for the Use of R in Regulated Clinical Trial Environments](https://www.r-project.org/doc/R-FDA.pdf). This includes source code management, testing and validation, release cycles, version archiving, qualified personnel, security and disaster recovery. This covers core and recommended packages. 

Some encouraging examples of contributed packages are: 

*	The tidyverse, which is a commercially supported collection of contributed R packages. Rstudio has provided [validation guidance](https://environments.rstudio.com/validation.html) for various packages including [tidyverse, tidymodels, r-lib, and gt](https://www.rstudio.com/assets/img/validation-tidy.pdf) as well as [shiny and rmarkdown](validation-shiny-rmd.pdf). If an organization feels comfortable to list the Rstudio development team as a trusted resource, all packages could be qualified.

*	Another early lighthouse project example is [stan](https://github.com/stan-dev), which is broadly used in the pharmaceutical industry. The development team has published the [Software Development Lifecycle](https://mc-stan.org/docs/sdlc.html). The layout and content of this document very closely follows the original publication by the R consortium. 

The members of the R validation executive committee like this trend and would be happy to see more of this. Package developers could consider providing information on SDLC or validation reports as vignettes. Recent package developments like [valtools](https://github.com/phuse-org/valtools) can support such efforts. 


