---
title: 'Status Update May 2022'
author: Juliane Manitz
date: '2022-05-20'
slug: status-update-may-2022
categories:
  - news
banner: 'img/banners/news.png'
---


It’s time to bring another update to you on the current status of the R validation hub:


*	The **`riskmetric` R package** has been stable on CRAN. Recent work has focused on structuring "cohort metrics" -- metrics that are conditioned on the package library or execution environment available to R. In R, package behaviors are often dependent on the rest of the R installation, and this new feature will help to make metrics more inspectible and reproducible, as well as allowing us to ask new questions like, "What would be the effect of installing a new package into an R environment?". Within `riskmetric`, cohorts will represent our way of capturing this information to help make the context of each metric more explicit. Eric Milliman has been leading this effort, representing the next major feature enhancement for the `riskmetric` package.

*	The *Riskmetric App* team have been working very hard to resolve all the major issues and add new features. We are happy to announce the news that they just published a beta version of the app and ask for feedback from the community. To access the app, you can go to [https://rinpharma.shinyapps.io/risk_assessment/](https://rinpharma.shinyapps.io/risk_assessment/) and follow the instructions for login. Please provide your [feedback in github](https://github.com/pharmaR/risk_assessment/issues/149). Next development goal is turning the app into an R package.

* Regarding *communications*, we have had a busy year 2021 with various conference contributions that are available on the [website presentation section](https://www.pharmar.org/present/). This year we will participate at useR! 2022, where our abstract was accepted. In the presentation, we will reflect on various examples of implementation of risk-based approaches to assess R package accuracy within a validated infrastructure.

*	In addition, we have initiated a presentation series on *case studies* where various companies share their experiences building a GxP framework with R highlighting aspects that were easy to implement which those which were more challenging. The first session was on April 26. You can find the [recording on youtube](https://www.youtube.com/watch?v=P2m6RmVViu0). Feel free to actively pitch into the [discussion on github](https://github.com/pharmaR/case_studies). Additional contributions are welcome! Follow-up sessions are scheduled for May 24th and June 14th. You can sign up by joining our [mailing list](https://urldefense.com/v3/__https:/www.pharmar.org/contact/__;!!LqrO4s96!mieVHBrLFhB_mlJ0hVRAb8pHjTWf7YNdfWBfX-exRAQVXHb6OTOX9zKdO5tUDm7AeuR6H9JnD2eIZ6eBmjw0B-9DqNg$).

*	*People & Future Directions:* Keaven and Yilong will be stepping back from the R Validation Hub executive committee. We are so grateful for the support that they have provided in helping steer the group and get us to where we are today (where we’re seemingly inundated with companies wanting to share what they’re doing to adopt R). For the good news, we are happy to welcome on board Preetham who is the current lead for package qualification at Merck & Co. If you are interested in taking an active role in helping to determine the direction of the R Validation Hub, please feel free to reach out to us. Future work may include building a repository with R packages relevant for submissions to regulatory agencies, consolidate current state of the art on testing qualification and other topics. However, we do need willing volunteers to help drive these initiatives forward.
