---
title: '{riskassessment} App voted best Shiny app at shinyConf 2023! 🎉'
author: Juliane Manitz
date: '2023-06-02'
slug: shiny_conf_award
categories:
  - news
tags:
  - risk assessment
banner: 'img/banners/shinyconf_win.png'
---

The `{riskassessment}` app, presented by Aaron Clark from the R Validation Hub Executive Committee, was voted best Shiny app at shinyConf 2023. The 2nd Annual Shiny Conference was held in March 2023. It was all virtual with over 4k global registrants. Congratulations!!

The app provides a shiny front-end to augment the utility of the `{riskmetric}` package, thus user-friendly and interactive access to risk assessment of R packages. The apps functionalities include: 

* Analyze risk metrics for each R package (and version) without the need to write code in R
* Encourage open-source mentality by contribution of user/reviewer comments
* Save overall assessment decision for each package (categories: low, medium, or high risk)
* Download reports with risk metrics outputs, and reviewer comments, and more
* Administration: All assessments are stored in a database and admins can manage users roles and metric weighting

Do you want to know more? Here some additional resources: 

* The Demo app: https://rinpharma.shinyapps.io/riskassessment/ 
* GitHub: https://github.com/pharmaR/riskassessment 
* User guide: https://pharmar.github.io/riskassessment/ 

*If you are interested in getting involved in contributing to our technical efforts then please send an email to [psi.aims.r.validation@gmail.com](mailto:psi.aims.r.validation@gmail.com).  Or join our [mailing list](https://www.pharmar.org/contact/) to receive an invite to our community meetings and receive notifications of new blog posts.*
