---
title: "Our Origins & Mission"
---

## Origins

The R Validation Hub was formed in 2018 by the [PSI AIMS Special Interest Group](https://psiweb.org/sigs-special-interest-groups/aims) and is supported by the R Consortium. We work closely with many neighboring efforts in the pharmaceutical space and broader R ecosystem.

## Mission

Our mission is to leverage the open-source and collaborative nature of R while supporting its adoption within the biopharmaceutical setting.

Since our inception, we have worked on developing several resources in hopes of their utilization industry-wide. Our solutions for the validation of R packages assist your work by quantifying the "risk" of R packages with several meaningful metrics (see {riskmetric}) and providing a user-friendly, full-fledged R Shiny app as a central hub to gauge the "risk" of packages for your organization (see {riskassessment}). These solutions are useful for a variety of roles, like individual contributors who are curious about a package's risk or an organization's administrator(s) for Posit Package Manager, for example.

While the R Validation Hub continues to evolve, we are enthusiastic about fostering enriching discussions through our community meetings and extending our presence at conferences or internally at organizations to progress the use and acceptance of R in our industry.
