---
title: Regulatory Metrics Repository
---

<style>
.showcase-content-container {
  display: flex;
  justify-content: center;
  width: 100%;
  overflow: hidden;
}

.showcase-content {
  box-shadow: 0 0 3em #0008;
  width: 90%;
}

@media (min-width: 768px) {
  .showcase-content {
    width: 60%;
  }
}

.embedded-video {
  height: auto;
  aspect-ratio: 16/9;
}

.card {
  margin: 0;
  padding: 0;
  overflow: hidden;
}

.card > * {
  padding: 0.5em 1em 0.5em 1em;
}

.card > h3 {
  padding: 0.5em 1em 0.5em 1em;
  margin: 0;
  margin-bottom: 0.8em;
  box-shadow: 0 -2em 2em 2em #0004;
  background-color: #dcdcdc;
}

.card-button {
  display: inline-block;
  background: #467fbf;
  color: white;
  padding: 0.75em 1.5em;
  font-size: 1.3em;
  font-weight: bold;
  border-radius: 0.25em;
}

.card-button:hover {
  background: #265f9f;
}

.card-button * {
  padding: 0;
  margin: 0;
}

.bg-gray {
  background-color: #dcdcdc;
}

.bg-light-gray {
  background-color: #f0f0f0;
}
</style>

## An open solution to regulatory quality

<div class="row">
<div class="col-sm-8">

Every regulatory submission requires evidence that the software used meets
quality standards appropriate for the type of work. The ***R Validation Hub***
proposed standards for this process in our [2020 White Paper](/white-paper).

</div>
<div class="col-sm-4">

`TODO: Graphic`

</div>
<div class="col-sm-8">

Now we're translating those standards into an open-source repository of
risk assessments, available to all. We hope to empower validation that is
**consistent**, **reproducible** and **transparent**, lowering the barrier
to entry for start-ups, empowering consistency among contract research
organizations (CROs), and improving the speed of regulatory review for
established enterprises.

</div>
</div>

<div style="padding-top: 2em;">
<div class="showcase-content-container bg-light-gray">
<iframe
class="showcase-content embedded-video"
src="https://www.youtube.com/embed/VS_t5IoQbOE"
title="R Validation Hub Workstream Updates"
frameborder="0"
allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
referrerpolicy="strict-origin-when-cross-origin"
allowfullscreen
></iframe>
</div>
</div>

<div class="text-center">
<div class="heading">

## Learn More

</div>

Want to get involved, or know someone who can help? [Contact us.](#TODO)

</div>

<div class="row">
<div class="col-sm-4" style="padding: 0.5em;">
<div class="card bg-light-gray text-center">
### Our Guidelines

<a href="#TODO">
<div class="card-button">
White Paper
</div>
</a>
Five years ago we drafted the guidelines. Today they're a _de facto_ industry
standard. Now we're building a repository of pre-calculated metrics to make
the guidelines easier to apply.
</div>
</div>

<div class="col-sm-4" style="padding: 0.5em;">
<div class="card bg-light-gray text-center">
### At a Glance

<a href="#TODO">
<div class="card-button">
Executive Summary
</div>
</a>
Read more about our ambitions, expected timelines and how we plan to get
there. Learn why businesses large and small are excited to see us moving
forward.
</div>
</div>

<div class="col-sm-4" style="padding: 0.5em;">
<div class="card bg-light-gray text-center">
### Presentations

<a href="#TODO">
<div class="card-button">
Project Overview
</div>
</a>
The project at a glance, designed to get you up to speed fast. Start here
for interested parties looking for ways to contribute as volunteers or
advocates.
</div>
</div>
</div>

<div class="heading text-center">
## Ready to Go
</div>

We're seeking dedicated developers (DevOps and Full Stack with familiarity in
R) to help drive this project forward.

* If you're ready to contribute, join us in `#wg-r-validation-hub-repo` on the [R Consortium Slack](http://slack.r-consortium.com/)
* If you're ready to fund development, `#TODO contribution site`

