---
title: "The {riskscore} Package"
---

A data package for cataloging riskmetric results across public repositories.

**WARNING:** Right now, the [`{riskscore}`](https://github.com/pharmaR/riskscore) is in a PoC stage that is not fully operational. With that said, there are several use cases that make the concept of {riskscore} valuable, including (but not limited to) the following: it ...

-   Guides more effective discussion around how to summarize risk
-   Helps communicate changes to `{riskmetric}`'s summarizing algorithm or interpretations of assessment data
-   Aids the `{riskmetric}` dev team in identifying "edge cases" for analysis and code refinement.
-   Provides a channel to distribute handy tools for building `{riskmetric}` result data (ie, mimicking how our process for external packages could serve as a useful template for when comparing to internal or private repos).
-   Allows everyone to report risk scores in terms of a "CRAN percentile" instead of just some arbitrary numeric value.
-   Establishes a central repository for package scores, which can be used for many applications, like generating badge scores or trending in a package's score over time to measure performance.

------------------------------------------------------------------------

#### Are you interested in supporting package development?

We could always use extra help/feedback! Please consider one of the following options:

-   [Propose a feature](https://github.com/pharmaR/riskscore/issues/new) for us to consider
-   [Join the dev team](https://www.pharmar.org/contribute/) - extra hands make light work
