---
title: Status Update July 2020
author: Juliane Manitz
date: '2020-07-20'
slug: status-update-july-2020
categories: [news]
tags:
  - riskmetric
banner: 'img/banners/news.png'
---

It’s time to bring some updates to you on the current status of the R validation hub and we are have plenty of great developments. 

Fission has finished their work on the R package risk assessment app and made the source code is [available on github](https:/github.com/pharmaR/risk_assessment). It is an interactive web application providing a front end for the collection of metrics for R packages via `riskmetric` package including visualizations and comparison metrics. 

This is a major milestone for us as the app becomes now a community effort. Fortunately, we are happy to announce that Marly Cormar who has agreed to take on the lead of the app development. With her on board, we are confident to have a next major version ready by R/Pharma 2020. 

In parallel, the ‘riskmetric’ R package made good advances and the respective support team is growing. In fact, they are putting a timeline together for a stable release soon. Stay tuned!

In other words, the R validation hub project is growing up and becomes a community effort that thrives and fails with your support – no pressure, but this is the perfect time to join the effort ;)

Furthermore, Andy presented at the EU Programming Heads meeting in June and earlier this month, Andy and Juliane recorded a presentation for the virtual useR! 2020, which is published on the R Consortium youtube channel. We can tell you that recording talks is so much more exhausting than giving them in person. Both presentations can be found on our [website](https:/www.pharmar.org/present/). 

Finally, you might have recognized that we initiated quarterly meeting, which start on July 21, 2020. We are looking forward to see you there! For invites to these meetings and occasional news updates, please join our [mailing list](https://lists.r-consortium.org/g/RConsortium-Validation-Hub). 

The R Validation Hub Executive Committee
