---
title: 'Status Update: R Validation Hub at R/Pharma 2021'
author: Juliane Manitz
date: '2021-10-19'
slug: status-update-R-pharma-2021
categories:
  - news
banner: 'img/banners/news.png'
---

Our favorite meeting of the year is approaching: [R/Pharma 2021](https://rinpharma.com/) will be held virtually November 2-4th, 2021. Also watch out for workshops the week before. 
Since the R validation Hub is closely associated with R/Pharma, we would like to highlight some of the presentations inspired by the R validation Hub, partner initiatives, or generally related to the topic of validation. 

**Tuesday: November 2, 2021**

*	11:00am “R Package Validation at Roche” by Coline Zeballos, Roche
*	11:20am “Statistical Analysis and Pathway to a Risk-based Assessment of R packages at Merck KGaA/EMD Serono” by Juliane Manitz, EMD Serono
*	1:50 PM “Panel Discussion – Validation” with representatives of the R validation Hub” 

**Wednesday: November 3, 2021**

*	11.40am “R Consortium Pharma Working Groups Overview and Updates” by Ning Leng, Roche
*	10:10am “Submitting Data to CDER: What Comes Next?” Heather Crandall and Paul Schuette, FDA
*	11:00am “Using {valtools} for software validation separate from development” Marie Vendettouli, Fred Hutch
*	1:00pm “Reimagine the R package distribution system for reproducible research and submissions” by Nan Xiao, Merck

**Thursday: November 4, 2021**

*	12:40pm “Performing a risk assessment of R packages using the Risk Assessment Shiny Application” by Marly Gotti, Biogen

**Friday: November 5, 2021**

*	10:00-13:00am Workshop “R Package Validation Framework” hosted by Ellis Hughes (gsk) & Marie Vendettuoli (Fred Hutch)

We are looking forward to see you at R/Pharma, hear your feedback and have engaging discussions. If you are not registered yet, [don’t wait to do so!](https://rinpharma.com/post/2021-09-21-registration/)



