---
title: 'Status Update: Conferences 2021'
author: Juliane Manitz
date: '2021-03-12'
slug: status-update-conferences-2021
categories:
  - news
tags:
  - riskmetric
  - risk assessment
  - white paper
banner: 'img/banners/news.png'
---

The new year is starting with some good news for the R validation hub. We will be able to present our work at a number of different meetings in 2021:

* [National Institute of Statistical Sciences](https://www.niss.org/events/niss-merck-meet-open-source-software-pharma) (NISS; April 21, 2021): NISS-Merck Meet-Up on Open Source Software in Pharma

* [Annual Meeting of Statisticians in the Pharmaceutical Industry](https://psiweb.org/conferences/about-the-conference) (PSI; June 21-23, 2021): Contributed session accepted

* [Joint Statistical Meetings](https://ww2.amstat.org/meetings/jsm/2021/) (JSM; August 7-12, 2021): Topic-contributed session accepted

* [ASA Biopharmaceutical Section Regulatory-Industry Statistics Workshop](https://ww2.amstat.org/meetings/biop/2021/) (September 21-23, 2021): Contributed session pre-selected and accepted

* Additional submissions are ongoing, so stay tuned for updates. All public presentations will be made available on the [presentations page](/present/).

Make sure to recommend our presentations and sessions to your colleagues and peers.
It is an opportunity to learn more about the work by the R validation hub supporting the adoption of R within a biopharmaceutical regulatory setting. We are looking forward to the interaction and feedback from the community.

*If you are interested in getting involved in contributing to our technical efforts then please send an email to [psi.aims.r.validation@gmail.com](mailto:psi.aims.r.validation@gmail.com).  Or join our [mailing list](https://lists.r-consortium.org/g/RConsortium-Validation-Hub) to receive an invite to our quarterly meeting and receive notifications of new blog posts.*
